### ISSUE TITLE
Theme directory emmoltes/symbolic of theme GNOME++ has no size field

### ISSUE THREAD

**Issue by diabolicle** [Bonandry/gnome-plus#13]
I'm getting this warning from gnome logs quite frequently. It would be nice if it was removed even though it seems harmless.

**Comment by Bonandry** [comment]
Thanks diabolicle for reporting
I understand where the problem is and I think I have solved it
if you want to solve immediately open index.theme and fix "emmoltes" with emotes, save and you have solved
![Schermata da 2019-05-07 20-58-11](https://user-images.githubusercontent.com/7957697/57325865-64216580-710b-11e9-83d9-199eea1cacb5.png)

**Comment by gusbemacbe** [comment]
@diabolicle 

We have fixed and updated it, but it is in the private repository. The next weeks we will release.

**Comment by gusbemacbe** [comment]
@diabolicle, upstreamed and upgraded. It is in the beta branch now.
