### ISSUE TITLE
Script for changing folder's color

### ISSUE THREAD

**Issue by mese79** [Bonandry/gnome-plus#26]
Hi
Very nice work!!
I just wonder is there any script for changing color of folder icons automatically? like [papirus-folder](https://github.com/PapirusDevelopmentTeam/papirus-folders)

**Comment by gusbemacbe** [comment]
Hi @mese79 !

The only script which can change the colour of Plus family - Adwaita++ (not compatible yet), Suru++, Suru++ Ubuntu and Yaru++ is [Suru++ Folders](https://github.com/gusbemacbe/suru-plus-folders), but it is outdated. I have to upgrade it to make it compatible with Adwaita++.

Papirus Folders is designed only for Papirus icons family because Papirus and Adwaita++ have different hierarchies.

**Comment by mese79** [comment]
I see.
> The only script which can change the colour of Plus family - Adwaita++ (not compatible yet), Suru++, Suru++ Ubuntu and Yaru++ is Suru++ Folders, but it is outdated. I have to upgrade it to make it compatible with Adwaita++.  

That would be great!

**Comment by gusbemacbe** [comment]
Hello @mese79 !

Sorry for our long absence because this project's author broke two repositories, including Adwaita++. I took 6 months to repair his repositories. 

Today I released a new version of Adwaita++, totally fixed. I forbid and will forbid the project author of breaking this repository. I have already created a protected repository against the mistakes of the project author. 

Now [Suru++ Folders](https://github.com/gusbemacbe/suru-plus-folders) supports finally official Adwaita++.
