### ISSUE TITLE
A variant with extra apps only?

### ISSUE THREAD

**Issue by ghost** [Bonandry/gnome-plus#34]
Hello guys, sorry I had a lot of work the last two weeks.

When I use vanilla GNOME, I like to stay with default Adwaita look'n'feel. The problem is that it lacks third-party apps icons, of course Adwaita++ solves that and it's great.

But imho it changes Adwaita a bit too much: places icons aren't the same, some actions/status symbols are missing or old or just different, some apps have an older style, etc...

To be honest it's why I don't use Adwaita++ anymore: too much different and sometimes outdated.

My suggestion is that you could ship another variant with ONLY icons for extra apps, inheriting default Adwaita in `index.theme` file. It would be much easier to maintain, and this way users still have an up-to-date icon theme that follows exactly the upstream, just with more apps included.

Thank you :sweat_smile:

**Comment by gusbemacbe** [comment]
Hello @DarthWound 

> But imho it changes Adwaita a bit too much: places icons aren't the same, some actions/status symbols are missing or old or just different, some apps have an older style, etc...

- Please, can you cay which places icons are not the same between Adwaita and Adwaita++? 
- Are you referring to missed KDE actions and status icons? @Bonandry  is limited only to Ubuntu GNOME. He is just a designer and does not know anything about the whole Linux system. 
- Which actions and status icons do you find old? You must know GNOME developers did not upgrade some actions and status icons for a decade and I have upgraded the battery icons.
- Which apps icons do you find olf-fashioned?

> My suggestion is that you could ship another variant with ONLY icons for extra apps, inheriting default Adwaita in `index.theme`

The `index.theme` is based on @SmartFinn's and @varlesh's Paprius `index.theme`. They follow the FreeDesktop rules. If I need to follow the original Adwaita's `index.theme`, I must reconfigure [Suru++ Folders](https://github.com/gusbemacbe/suru-plus-folders), but @SmartFinn told me that script would not wok for icons themes which have different hierarchies (for example, . icons theme A has a `places/scalable`, icons theme B has `256x256/places` and icons theme C has `scalable/places`). You must analyse my repo and see if it is possible and easy to reconfigure. 

The problem is that, Adwaita's hierarchy is always `size/type`, and I find it too challenging, because resymlinking the type folders from the size folders is too complicated.

**Comment by ghost** [comment]
>  Please, can you cay which places icons are not the same between Adwaita and Adwaita++?

All the folders.

>  Are you referring to missed KDE actions and status icons? @Bonandry  is limited only to Ubuntu GNOME. He is just a designer and does not know anything about the whole Linux system.

Nope. But maybe I was wrong for this point sorry. Some panel icons aren't ok though, like the GNOME Tweaks symbolic which is now different in Adwaita, or network icon as you use the one from Papirus.

>  Which apps icons do you find olf-fashioned?

I don't remember right now, but some of them changed in 3.34-3.36, sometimes it's just a subtle change like shadow or color correction, but it's still important.

> The `index.theme` is based on @SmartFinn's and @varlesh's Paprius `index.theme`. They follow the FreeDesktop rules. If I need to follow the original Adwaita's `index.theme`, I must reconfigure [Suru++ Folders](https://github.com/gusbemacbe/suru-plus-folders), but @SmartFinn told me that script would not wok for icons themes which have different hierarchies (for example, . icons theme A has a `places/scalable`, icons theme B has `256x256/places` and icons theme C has `scalable/places`). You must analyse my repo and see if it is possible and easy to reconfigure.

I meant just add Adwaita in the inherits list if you make a variant with only extra apps, so it will use the standard Adwaita for other existing icons.

> You must know GNOME developers did not upgrade some actions and status icons for a decade and I have upgraded the battery icons.

Yeah, but they are working on it, some of them were already improved in 3.34-3.36, and anyway if we have a variant that follows upstream it doesn't matter that much.

- - -

Just to be sure that you understand what I am suggesting, it would be just a theme that adds icons for missing third-party programs without modifying the original Adwaita set.

- - -

A few examples of differences between Adwaita and Adwaita++ _(Fedora 31 & GNOME 3.34)_:

![diff](https://user-images.githubusercontent.com/1771322/75158301-1e736f00-5716-11ea-9332-f1c197310950.png)

**Comment by gusbemacbe** [comment]
Hello @DarthWound 

@Bonandry does not like to follow Adwaita's GNOME developers rules. But I will negotiate with him. If he agrees, I will reform the icons themes, paying attention to the whole Adwaita project. 

> I meant just add Adwaita in the inherits list if you make a variant with only extra apps, so it will use the standard Adwaita for other existing icons.

Ah, only the third-party icons who do not exist on the original Adwaita icons theme, and no need to add all the icons as the Adwaita has already. But is it possible that it inherit from the original Adwaita icons theme if it uses SVG and original Adwaita uses PNG, and they have different hierarchies? 

There are three problems:

- In Adwaita++'s `places/scalable`, there are folders colours and is a folders default colour. The folder default colour is `folder-adwaita-*`. If the user uses the Suru++ Folders to replace the folder colour, the folders inherited from the original Adwaita will not be replaced with another colour because these icons themes are separated and Adwaita's places icons are PNG.
- The user will use @actionless' [Oomox](https://github.com/themix-project/oomox) to replace the colour of all monochromatic icons and the folders. The icons of original Adwaita icons theme are PNG and can not be replaced. 
- What if the user does not want to install the original Adwaita icons theme? I know that Adwaita will come as default on GNOME distributions and on Ubuntu-based distributions, but and Arch Linux and Void Linux which do not come with Adwaita?

**Comment by ghost** [comment]
> Bonandry does not like to follow Adwaita's GNOME developers rules. But I will negotiate with him. If he agrees, I will reform the icons themes, paying attention to the whole Adwaita project.

Yes I know haha :laughing: same "problem" with Yaru++, but imo a "++" theme should only add missing stuff to vanilla, not modify it too much. It's why I'm suggesting a more upstream-friendly variant. But I didn't ask to give up the current work, just offer another variant for people who prefer the original Adwaita. And there are a lot.

> Ah, only the third-party icons who do not exist on the original Adwaita icons theme, and no need to add all the icons as the Adwaita has already.

Exactly!

>But is it possible that it inherit from the original Adwaita icons theme if it uses SVG and original Adwaita uses PNG, and they have different hierarchies?

Good question, I don't know. In worst case scenario, maybe provide existing icons in SVG but don't modify them and keep them up-to-date with upstream.

> In Adwaita++'s `places/scalable`, there are folders colours and is a folders default colour. The folder default colour is `folder-adwaita-*`. If the user uses the Suru++ Folders to replace the folder colour, the folders inherited from the original Adwaita will not be replaced with another colour because these icons themes are separated and Adwaita's places icons are PNG.

If an user wants to change folder colors, then he uses the current Adwaita++ with its modified folders.

> The user will use @actionless' [Oomox](https://github.com/themix-project/oomox) to replace the colour of all monochromatic icons and the folders. The icons of original Adwaita icons theme are PNG and can not be replaced.

Same answer than the previous one.

> What if the user does not want to install the original Adwaita icons theme? I know that Adwaita will come as default on GNOME distributions and on Ubuntu-based distributions, but and Arch Linux and Void Linux which do not come with Adwaita?

An user that wants an upstream-friendly Adwaita++ probably already has the original Adwaita installed. And if not, I don't think it's complicated for a Void _(or Arch/whatever)_ user to type `sudo xbps-install -S adwaita-icon-theme-full`. It's as simple as installing your icon theme, just one command.

- - -

I don't want to annoy you, it's just that a lot of users like vanilla icons _(Adwaita or Yaru)_ and just need missing programs to have a consistent look. And I'm one of them. For example, look at what @varlesh _(from Papirus Team)_ did in [breeze-extra](https://github.com/varlesh/breeze-extra), he's added _(and slightly improved)_ some icons but didn't change the original Breeze theme, and that's enough to have an excellent enhanced Breeze in KDE.

**Comment by gusbemacbe** [comment]
@DarthWound 

I need to think strategically how to reorganise the Adwaita++ themes, if @Bonandry does not agree:

We will have two repositories:

- Adwaita++ Full:
   - This Adwaita++ will be renamed Adwaita++ Full;
   - Many icons will be redesigned, following the Adwaita project;


- Adwaita++ Minimal:
  - It will contain only third-party icons, including Breeze icons and @varlesh's Breeze Extra;
  - Totally in PNG or SVG (recommended);
  - It will inherit from Adwaita;
  - It will follow Adwaita's hierarchy;
  - It will not have folders colours;
  - The Arch/Void script will require the installation of GNOME's Adwaita. 

What do you think?

**Comment by ghost** [comment]
Sounds great!

But why the Breeze icons in "Adwaita++ Minimal"? Maybe you misunderstood me, I wasn't telling you to add them, it was just an example of what varlesh did, Breeze with more icons without altering it.

**Comment by gusbemacbe** [comment]
> But why the Breeze icons in "Adwaita++ Minimal"? 

The original Adwaita is not fully supported in KDE. It does not have many KDE actions, apps and status icons. 

The most important observation is that, I have upgraded the battery icons because @btd1337 found the current battery icons of original Adwaita ugly and old-fashioned, he hates them. He also hates the old legacy icons. 

I have been discussing the legacy icons which are old-fashioned with the people from Ubuntu's original Yaru, you can see our discussion:

https://github.com/ubuntu/yaru/issues/1912

@Feichtmeier  and @madsrh have decided to upgrade the legacy icons still used by modern apps as Inkscape, Meld and Transmission. You can see another discussion: 

https://github.com/ubuntu/yaru/issues/1965

**Comment by ghost** [comment]
> The original Adwaita is not fully supported in KDE. It does not have many KDE actions, apps and status icons.

I'm not sure if it's really needed. GNOME and KDE design guidelines are really different, mixing Adwaita and Breeze sounds weird. And it adds much more work to maintain everything. At least maybe "Adwaita++ Minimal" should only focus on GNOME _(or GTK desktops more globally)_.

> The most important observation is that, I have upgraded the battery icons because @btd1337 found the current battery icons of original Adwaita ugly and old-fashioned, he hates them. He also hates the old legacy icons.

Well, I agree that some icons are a bit ugly, but that's part of upstream. Didn't they improve the battery icons recently? I think I've read something about this topic some weeks ago, but I didn't pay attention as I don't have any laptops with GNOME.

It's ok to improve some stuff, but not too much imo, as it may alter upstream's design and add more work to do _(= harder to maintain and keep up-to-date)_. But that's just my two cents :-)

**Comment by actionless** [comment]
> The user will use @actionless' Oomox to replace the colour of all monochromatic icons and the folders. The icons of original Adwaita icons theme are PNG and can not be replaced.

@gusbemacbe  is there an oomox-plugin somewhere for these icons?

**Comment by gusbemacbe** [comment]
Hello @DarthWound 

> At least maybe "Adwaita++ Minimal" should only focus on GNOME (or GTK desktops more globally).

@Bonandry would be happy with it.

If some KDE users want me to include Breeze and KDE icons to Adwaita++ Minimal, maybe I will create another alternative icons theme – Adwaita++ Minimal KDE. But Adwaita++ Full is already efficient. 

Too many alternative icons themes. LOL

@actionless

> @gusbemacbe is there an oomox-plugin somewhere for these icons?

No, I did not do a plugin for Adwaita++ for Oomox. But I will do. 

I did not update my own Suru++ projects for months as I have said you before, because I was overly dedicated to Adwaita++ and Yaru++ projects @Bonandry broke. I already forbade him of messing the git and mixing and breaking them with old Suru++ Ubuntu.

**Comment by ghost** [comment]
> > At least maybe "Adwaita++ Minimal" should only focus on GNOME (or GTK desktops more globally).
> 
> @Bonandry would be happy with it.

It makes sense for me.

> If some KDE users want me to include Breeze and KDE icons to Adwaita++ Minimal, maybe I will create another alternative icons theme – Adwaita++ Minimal KDE. But Adwaita++ Full is already efficient.

Yeah I agree, just support KDE icons in Adwaita++ Full. But of course with GNOME design, like what varlesh did in his Breeze-Extra theme, he added icons for GNOME but respected the Plasma look.

> Too many alternative icons themes. LOL

:rofl: I'm sorry lol, but I think you understand my point of view regarding a "minimal" variant.

**Comment by actionless** [comment]
btw in themix forks of GNOME-Colors and Archdroid icons KDE icons are set as fallbacks:

https://github.com/themix-project/gnome-colors-icon-theme/blob/master/gnome-colors/src/index.theme#L4
https://github.com/themix-project/archdroid-icon-theme/blob/master/archdroid-icon-theme/index.theme#L3

otherwise opening Dolphin or other kde app ends up with only half of icons on its toolbar

**Comment by ghost** [comment]
@gusbemacbe Hello, I hope you're fine guys, as you're inactive since quite a long time now.

**Comment by gusbemacbe** [comment]
Hello @DarthWound 

I and Andrea are fine. I am going to focus on Adwaita++.

**Comment by gusbemacbe** [comment]
Hello @DarthWound and @actionless! 

There's a small problem. Adwaita does not contain colourful apps icons. Only symbolic and monochromatic icons, then it is very hard to remove the unnecessary icons to make Adwaita++ minimal.
