### ISSUE TITLE
Icons Request

### ISSUE THREAD

**Issue by ghost** [Bonandry/gnome-plus#36]
**M I N E C R A F T**

- minecraft.svg
- minecraft-launcher.svg

![minecraft](https://user-images.githubusercontent.com/1771322/77102445-22469880-6a19-11ea-9ea9-11a7653d21fc.png)

---

**R E A P E R**

- cockos-reaper.svg

![main](https://user-images.githubusercontent.com/1771322/77102417-165ad680-6a19-11ea-87ec-3e2c8da453ab.png)

**Comment by ghost** [comment]
@gusbemacbe Hello guys, are you still working on this icon set?

**Comment by gusbemacbe** [comment]
Hello @DarthWound 

Sorry for my longer absence since March where the COVID-19 outbreak came out. No, I am not yet. Today I must finish my little backup and finish Dracula proejct, and return to @Bonandry's projects. I will explain what happened with me since March. 

In late March, I was working with these projects, but the COVID-19 outbreak came out, I had to shelter myself in another "sanctuary bedroom" for isolating myself from my family, because they did not practice the hygiene and quarantine rules and I suspected they were asymptomatic and had COVID-19 symptoms. I had to stay at the sanctuary bedroom for 2 months. My computer was at my bedroom and I could not go to my bedroom because of my family. I brought my laptop, but my laptop came with Windows and it did not go well with Andrea's projects, even with WSL 2.

In May, I had light COVID-19 symptoms because my sister was asymptomatic, had it and never respected the social distancing with me, and I had to stay at bed for a month. As I got better, I brought my computer to the sanctuary bedroom. 

In early June, I got discharged, have been training i3 to which I migrated from KDE, and was about to return to Dracula project and Andrea's, but I was in much hurry to back up my whole dotfiles to an external SSD, GitLab and Mega because the X display manager broke. I was about to finish the back up that week, but last week, I could not complete another small backup and work with these projects, because I received a notification from the bank that somebody cloned my credit card and tried to buy a thing without my authorisation, then I had to go to bank. And an e-mail from a Buddhist temple's IT manager about my account. I told her I never went to any Buddhist temple. She has informed that somebody used my name and my e-mail for account to watch the streaming. 

Today I am about to finish the small back up for SSD and Mega (I have completed the back up for GitLab), then I will return to the projects.

I am a very sorry for my longer absence!

**Comment by ghost** [comment]
Hi @gusbemacbe 

No problem, it's what I guessed, sorry for your problems related to COVID-19.

**Comment by Brin-o** [comment]
Hey @gusbemacbe - if you would be willing to incorporate them in the icon theme I don't mind making these icons btu I have no experience creating icon packs out of icons themselves and I feel it would be a bit redundant for me to try to fork this whole thing to add 2 icons.

**Comment by gusbemacbe** [comment]
@Brin-o 

You will fork from the branch `gusbemacbe`, but you do not need to clone locally, you just drag and drop the icons in your forked repo, and make a pull request to my branch `gusbemacbe`.

**Comment by gusbemacbe** [comment]
Ciao @Bonandry 

Per favore aggiunge le icone Minecraft e Reaper alla branch `master` del repositorio `adwaita-plus-privato`. Anche aggiunge molte icone perdute di Yaru++ al repositorio, come Microsoft Edge, etc.

**Comment by gusbemacbe** [comment]
:gb: Added icons
:it:  Aggiunte icone
:fr: Icônes ajoutées
